//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPIForVOICEVOX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAPIForVOICEVOX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a  ア
        ///a&apos;s  エイズ
        ///a.  エイ
        ///a.&apos;s  エイズ
        ///a.d.  エイディー
        ///a.m.  エイエム
        ///a.s  エイズ
        ///a42128  エイフォーチューワンチュウェイト
        ///aa  エイエイ
        ///aaa  トリパレイ
        ///aaai  トリパレイヤイ
        ///aaberg  アバーグ
        ///aachen  アケン
        ///aachener  アケナー
        ///aah  ア
        ///aaker  アカー
        ///aaliyah  アリア
        ///aalseth  アルセス
        ///aamodt  アモト
        ///aancor  アンコー
        ///aardema  アーデマ
        ///aardvark  アードバーク
        ///aardvarks  アードバークス
        ///aargh  アーグ
        ///aarhus  アフース
        ///aaron  エロン
        ///aaron&apos;s  エロンズ
        ///aarons  エロンズ
        ///aaronson  エロンソン
        ///aaronson&apos;s  エロンソンズ
        ///aarti  アーティー
        ///aase  アス
        ///aasen  アセン
        ///ab  アブ
        ///aba  エイビエイ
        ///ababa  アババ
        ///abacha  アバカ
        ///aback  アバク
        ///abaco  アバコ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eng2kanaDict {
            get {
                return ResourceManager.GetString("eng2kanaDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream エンジンエラーです {
            get {
                return ResourceManager.GetStream("エンジンエラーです", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ボイスボックスが見つかりません {
            get {
                return ResourceManager.GetStream("ボイスボックスが見つかりません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ボイスボックスと通信ができません {
            get {
                return ResourceManager.GetStream("ボイスボックスと通信ができません", resourceCulture);
            }
        }
    }
}
